FROM tensorflow/tensorflow:latest-jupyter as tf-base

RUN apt-get update &&\
    apt-get install -y \
    g++ \
    r-base \
    r-base-dev \
    build-essential \
    curl \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ipython \
    ipython-sql \
    rpy2 \
    jupyterlab \
    jupyterlab_sos \
    sos-rmarkdown \
    numpy \
    pandas \
    matplotlib \
    seaborn \
    scikit-learn \
    scikit-image

RUN Rscript -e "install.packages(c('Hmisc',\
     'reticulate', \
     'foreach', \
        'doParallel', \
        'mice', \
     'remotes', \
     'IRkernel', \
     'languageserver'), \
     repos = 'http://cran.us.r-project.org')"\
      --no-save && \
    rm -rf /tmp/R*


EXPOSE 8888
CMD ["jupyter", "lab", "-p 8888", "--no-browser"]